#!/bin/sh

# Constants
SBCL="sbcl"
CCL="ccl"

lisp=$1;

if [ $SBCL = "$lisp" ] || [ $CCL = "$lisp" ];
then
  # Consume first arguemnt.
  shift;
else
  lisp=$SBCL;
fi

if [ $SBCL = "$lisp" ];
then
  sbcl --load quicklisp.lisp \
       --eval "(load \"quicklisp.lisp\")" \
       --eval "(quicklisp-quickstart:install :path \"./quicklisp\")" \
       --eval "(ql:quickload \"hunchentoot\")" \
       --load app.lisp \
       --eval "(compile-program \"app\" #'main)"
fi

if [ "$CCL" = "$lisp" ];
then
  if [ "Linux" = $(uname) ];
  then
    if [ "x86_64" = $(uname -m) ];
    then
      ccl="lx86cl64";
    else
      ccl="lx86cl";
    fi
  elif [ "Darwin" = $(uname) ];
  then
    if [ "x86_64" = $(uname -m) ];
    then
      ccl="dx86cl64";
    else
      ccl="dx86cl";
    fi
  elif [ "FreeBSD" = $(uname) ];  # Untested
  then
    if [ "x86_64" = $(uname -m) ];
    then
      ccl="fx86cl64";
    else
      ccl="fx86cl";
    fi
  elif [ "SunOS" = $(uname) ];  # Untested
  then
    if [ "x86_64" = $(uname -m) ];
    then
      ccl="sx86cl64";
    else
      ccl="sx86cl";
    fi
  else
    echo "Unsupported platform" >&2;
    exit 1;
  fi

  "$ccl" --load quicklisp.lisp \
         --eval "(quicklisp-quickstart:install :path \"./quicklisp\")" \
         --eval "(ql:quickload \"hunchentoot\")" \
         --load app.lisp \
         --eval "(compile-program \"app\" #'main)"
  exit 0;
fi
